version: "3.9"
services:

#  redis:
#    image: redis:latest
#    container_name: egg-redis
#    ports:
#      - 6379:6379
#    volumes:
#      - ./redis/data:/data
#      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
#    labels:
#      - "name=redis"
#      - "mode=standalone"
#    restart: always
#    command: redis-server /usr/local/conf/redis.conf

  nginx:
    image: nginx
    container_name: egg-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/servers:/etc/nginx/servers:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: egg-elasticsearch
    environment:
      - node.name=es-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200 # https
      - 9300:9300 # tcp
    networks:
      - es-bridge

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: egg-kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    # Elasticsearch Start Dependency
    depends_on:
      - elasticsearch
    networks:
      - es-bridge

  mongodb:
    image: yisc/mongo-arm64
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/seungyunlee/Programming/Final/spark-yarn-docker-main/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mydb

  fastapi:
    image: yisc/fastapi-arm64
    container_name: fastapi
    ports:
      - '8000:8080'
    volumes:
      - /Users/seungyunlee/Programming/Final/spark-yarn-docker-main/fastapi/src:/src
    working_dir: /src
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload


networks:
  es-bridge:
    driver: bridge