version: "3.9"
services:
  redis_container:
    image: redis:latest
    container_name: local-docker-redis-egg
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 3306:3306


